In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
df=pd.read_csv('https://raw.githubusercontent.com/rahul15197/Disease-Detection-based-on-Symptoms/master/Dataset/dis_sym_dataset_comb.csv')
df

label_dis  abdominal cramp  abdominal distention  abnormal behavior  \
0          Abscess                0                     0                  0   
1          Abscess                0                     0                  0   
2          Abscess                0                     0                  0   
3          Abscess                0                     0                  0   
4          Abscess                0                     0                  0   
...            ...              ...                   ...                ...   
8830  papilloedema                0                     0                  0   
8831  papilloedema                0                     0                  0   
8832  papilloedema                0                     0                  0   
8833  papilloedema                0                     0                  0   
8834  papilloedema                0                     0                  0   

      abnormal bleeding  abnormal sensation  abnormally frequent  abscess  \
0                     0                   0                    0        0   
1                     0                   0                    0        0   
2                     0                   0                    0        0   
3                     0                   0                    0        0   
4                     0                   0                    0        0   
...                 ...                 ...                  ...      ...   
8830                  0                   0                    0        0   
8831                  0                   0                    0        0   
8832                  0                   0                    0        0   
8833                  0                   0                    0        0   
8834                  0                   0                    0        0   

      aching  acne  ...  wet  wheezing  white patch vaginal discharge  \
0          0     0  ...    0         0                              0   
1          0     0  ...    0         0                              0   
2          0     0  ...    0         0                              0   
3          0     0  ...    0         0                              0   
4          0     0  ...    0         0                              0   
...      ...   ...  ...  ...       ...                            ...   
8830       0     0  ...    0         0                              0   
8831       0     0  ...    0         0                              0   
8832       0     0  ...    0         0                              0   
8833       0     0  ...    0         0                              0   
8834       0     0  ...    0         0                              0   

      widespread pain  withdrawal occurring stopping  worrying  yellow skin  \
0                   0                              0         0            0   
1                   0                              0         0            0   
2                   0                              0         0            0   
3                   0                              0         0            0   
4                   0                              0         0            0   
...               ...                            ...       ...          ...   
8830                0                              0         0            0   
8831                0                              0         0            0   
8832                0                              0         0            0   
8833                0                              0         0            0   
8834                0                              0         0            0   

      yellowish coloration skin white eye  yellowish skin  \
0                                       0               0   
1                                       0               0   
2                                       0               0   
3                                       0            

In [2]:
num_rows, num_cols = df.shape
print(num_rows)
print(num_cols)

8835
490


In [3]:
z=np.unique(df['label_dis'])
print(z)
print(z.size)

['Abscess' 'Acquired Capillary Haemangioma of Eyelid'
 'Acquired Immuno Deficiency Syndrome' 'Acute encephalitis syndrome'
 'Adult Inclusion Conjunctivitis' 'Alcohol Abuse and Alcoholism'
 'Alopecia (hair loss)' 'Alzheimer' 'Amaurosis Fugax' 'Amblyopia'
 'Amoebiasis' 'Anaemia' 'Aniseikonia' 'Anisometropia'
 'Antepartum hemorrhage (Bleeding in late pregnancy)' 'Anthrax' 'Anxiety'
 'Appendicitis' 'Arthritis' 'Asbestos-related diseases'
 'Aseptic meningitis' 'Asthma' 'Astigmatism' 'Atrophy' 'Autism'
 'Bad Breath (Halitosis)' "Bell's Palsy" 'Beriberi' 'Black Death'
 'Bleeding Gums' 'Blindness' 'Botulism' 'Brain Tumour'
 'Breast Cancer / Carcinoma' 'Bronchitis' 'Brucellosis' 'Bubonic plague'
 'Bunion' 'Burns' 'Calculi' 'Campylobacter infection' 'Cancer'
 'Candidiasis' 'Carbon monoxide poisoning' 'Carpal Tunnel Syndrome'
 'Cavities' 'Celiacs disease' 'Cerebral palsy' 'Chagas disease'
 'Chalazion' 'Chickenpox' 'Chikungunya Fever' 'Childhood Exotropia'
 'Chlamydia' 'Cholera' 'Chorea' 'Chronic 

In [4]:
df['label_dis'][28]

'Acute encephalitis syndrome'

In [5]:
#checking for null values
#The function df.isnull() returns a DataFrame containing True values 
# for any cells in df that are null (i.e. contain missing data), 
# and False otherwise. The method any(axis=0) then checks for any 
# True values in each column of the resulting DataFrame. 
# Finally, any() checks if there is at least one True value in all columns.
if df.isnull().any(axis=0).any():
    print("There is at least one column with null values")
else:
    print("There are no null values")

There are no null values


In [6]:
#[:, 0] selects all rows and the first column, which becomes the target variable y. 
#[:, 1:] selects all rows and all columns starting from the second column, which become the input features X.
y = df.iloc[:, 0].values
X = df.iloc[:, 1:].values
print(y)
print(X)
print(X.shape)

['Abscess' 'Abscess' 'Abscess' ... 'papilloedema' 'papilloedema'
 'papilloedema']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(8835, 489)


In [7]:
from sklearn.preprocessing import LabelBinarizer
encoder = LabelBinarizer()
y = encoder.fit_transform(y)
print(y)
print(y.shape)

[[1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]]
(8835, 261)


In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


In [10]:
model = Sequential()
model.add(Dense(256, input_dim=X.shape[1], activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(y.shape[1], activation='softmax'))

In [11]:
# compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


In [12]:
from keras.callbacks import ModelCheckpoint,EarlyStopping
#EarlyStopping-Stop training when a monitored metric(loss or accuracy) has stopped improving.
es=EarlyStopping(monitor='val_accuracy',min_delta=0.01,patience=3,verbose=1)
#ModelCheckpoint-to save a model or weights (in a checkpoint file) at some interval, so the model or weights can be loaded later to continue the training from the state saved.
mc=ModelCheckpoint(filepath="best_model.h5",monitor='val_accuracy',minDelta=0.01,patience=5,verbose=1,save_best_only=True)
cb=[es,mc] #it is an array

In [13]:
# fit the model
history = model.fit(X_train, y_train, epochs=100,callbacks=cb, batch_size=32, validation_data=(X_test, y_test))


Epoch 1/100
220/221 [============================>.] - ETA: 0s - loss: 2.6430 - accuracy: 0.5317
Epoch 1: val_accuracy improved from -inf to 0.71986, saving model to best_model.h5
221/221 [==============================] - 8s 25ms/step - loss: 2.6369 - accuracy: 0.5328 - val_loss: 1.6278 - val_accuracy: 0.7199
Epoch 2/100
221/221 [==============================] - ETA: 0s - loss: 1.0999 - accuracy: 0.8120
Epoch 2: val_accuracy improved from 0.71986 to 0.83135, saving model to best_model.h5
221/221 [==============================] - 5s 23ms/step - loss: 1.0999 - accuracy: 0.8120 - val_loss: 0.9549 - val_accuracy: 0.8314
Epoch 3/100
219/221 [============================>.] - ETA: 0s - loss: 0.6584 - accuracy: 0.8684
Epoch 3: val_accuracy improved from 0.83135 to 0.87153, saving model to best_model.h5
221/221 [==============================] - 3s 16ms/step - loss: 0.6575 - accuracy: 0.8686 - val_loss: 0.6795 - val_accuracy: 0.8715
Epoch 4/100
217/221 [============================>.] - ETA

In [14]:
# evaluate the model on test data
test_loss, test_acc = model.evaluate(X_test, y_test)
print('Test accuracy:', test_acc)

56/56 [==============================] - 0s 2ms/step - loss: 0.4755 - accuracy: 0.8919
Test accuracy: 0.8919072151184082


Prediction 


In [15]:
col_names = list(df.columns[1:])
print(col_names)

['abdominal cramp', 'abdominal distention', 'abnormal behavior', 'abnormal bleeding', 'abnormal sensation', 'abnormally frequent', 'abscess', 'aching', 'acne', 'acquiring drinking alcohol taking lot time', 'affected part turning white', 'anemia', 'anxiety', 'arm', 'attack pain', 'back', 'bacterial infection', 'bad breath', 'bad smelling thin vaginal discharge', 'bad smelling vaginal discharge', 'barky cough', 'belching', 'better sitting worse lying', 'birth baby younger week gestational age', 'bleeding gum', 'bleeding skin', 'blindness', 'blindness one eye', 'blister sunlight', 'bloating', 'blood stool', 'blood urine', 'bloody diarrhea', 'blue', 'bluish skin coloration', 'blurred vision', 'blurry vision', 'body tremor', 'bone pain', 'bowed leg', 'breakdown skeletal muscle', 'breathing problem', 'bruising', 'burning', 'burning redness eye', 'burning stabbing pain', 'burning urination', 'certain thought repeatedly', 'change bowel movement', 'change breast shape', 'change color', 'change 

In [16]:
for i,symptom in enumerate(col_names):
  print(f"{i}.{symptom}")

0.abdominal cramp
1.abdominal distention
2.abnormal behavior
3.abnormal bleeding
4.abnormal sensation
5.abnormally frequent
6.abscess
7.aching
8.acne
9.acquiring drinking alcohol taking lot time
10.affected part turning white
11.anemia
12.anxiety
13.arm
14.attack pain
15.back
16.bacterial infection
17.bad breath
18.bad smelling thin vaginal discharge
19.bad smelling vaginal discharge
20.barky cough
21.belching
22.better sitting worse lying
23.birth baby younger week gestational age
24.bleeding gum
25.bleeding skin
26.blindness
27.blindness one eye
28.blister sunlight
29.bloating
30.blood stool
31.blood urine
32.bloody diarrhea
33.blue
34.bluish skin coloration
35.blurred vision
36.blurry vision
37.body tremor
38.bone pain
39.bowed leg
40.breakdown skeletal muscle
41.breathing problem
42.bruising
43.burning
44.burning redness eye
45.burning stabbing pain
46.burning urination
47.certain thought repeatedly
48.change bowel movement
49.change breast shape
50.change color
51.change hair
52.c

In [17]:
symp=[]
more=True
while more!=False:
  id=int(input(print("Enter the id of symptom")))
  symp.append(id)
  forward=input("Want to continue? y/n")
  if forward.lower() == "n":
    more=False




Enter the id of symptom


KeyboardInterrupt: ignored

In [ ]:
symptoms = np.zeros(489, dtype=int)
for i in symp:
  symptoms[i]=1



In [ ]:
print(symptoms)
print(type(symptoms))

In [ ]:
diseases_names=list(z)
diseases_names

In [ ]:
probabilities = model.predict(symptoms.reshape(1, -1))
probabilities.shape

In [ ]:
probabilities

In [ ]:
predicted_class = np.argmax(probabilities, axis=-1)
print(predicted_class)
print(predicted_class.shape)
predicted_class = predicted_class.reshape(-1, 1)
print(predicted_class.shape)#as the inverse_transform require 2D array

In [ ]:
print(predicted_class[0][0])
print(diseases_names[predicted_class[0][0]])


In [ ]:
z[predicted_class[0][0]]

Saving diseases names

In [ ]:
import pickle

pickle.dump(diseases_names,open('diseases_names.pkl','wb'))

In [ ]:
# arr = np.array([[1, 2, 3, 4],
#                 [5, 6, 7, 8],
#                 [9, 10, 11, 12]])
# print(np.argmax(arr, axis=-1))
# print(np.argmax(arr, axis=1))

In [ ]:
#symptoms = np.zeros(489, dtype=int)
#assigning zeroes to all

In [ ]:
# for i, symptom in enumerate(col_names):
#     answer = input(f"Do you have {symptom}? (y/n)")
#     if answer.lower() == "y":
#         symptoms[i] = 1

In [ ]:
# symptoms = [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
# print(symptoms)
# type(symptoms)
# symptoms=np.array(symptoms)
# print(symptoms.size)

In [ ]:
# type(symptoms)
# symptoms=symptoms.tolist()
# type(symptoms)
# print(symptoms)

In [ ]:
# a=np.array([0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 00 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 00 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 00 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 00 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 00 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 00 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 00 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 00 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 00 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 00 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 00 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 00 0 0 0 0 0 0 0])

In [ ]:
# print(symptoms)

In [ ]:
# for i,symptom in enumerate(col_names):
#   print(f"<label><input type='checkbox' name='symptoms[]' value='{i}'>{symptom}</label><br>")